waf: Add null check for rtems_tools
If 'waf configure' is called without --rtems-tools, it'll be set to
None, leading to a TypeError.

Traceback (most recent call last):
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Configure.py", line 128, in execute
    super(ConfigurationContext,self).execute()
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/cdesai/rtems/examples-v2/wscript", line 29, in configure
    rtems.configure(conf)
  File "/home/cdesai/rtems/examples-v2/rtems_waf/rtems.py", line 158, in configure
    tools = _find_tools(conf, arch, [rtems_path] + rtems_tools, tools)
TypeError: can only concatenate list (not "NoneType") to list