posix_api: Pass needed argument to posix check
Fixes commit 579cc3c468c0dc923e37474e38c778bc2d085382

Traceback (most recent call last):
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Scripting.py", line 351, in execute
    return execute_method(self)
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Build.py", line 106, in execute
    self.execute_build()
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Build.py", line 109, in execute_build
    self.recurse([self.run_dir])
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/cdesai/rtems/examples-v2/wscript", line 45, in build
    bld.recurse('posix_api')
  File "/home/cdesai/bin/.waf-1.7.13-8c328f55ac27cdb03b8c949f189bbac3/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/cdesai/rtems/examples-v2/posix_api/wscript", line 9, in build
    if rtems.check_posix():
TypeError: check_posix() takes exactly 1 argument (0 given)